### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by kaushikc44** [lighthouse-web3/gitbook#8]
![image](https://user-images.githubusercontent.com/59849731/205459610-14c6da1f-d486-48ce-ae87-ff2ef84d07c3.png)
I guess it should be shareFile instead of decrypt also the shareFile isn't really working.

**Comment by nandit123** [comment]
We have updated the [code example](https://docs.lighthouse.storage/lighthouse-1/lighthouse-sdk/code-examples/browser-frontend/share-file-browser); thanks for reporting
